# Generated by Django 5.0.4 on 2026-03-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_patientprofile_gender_alter_user_phone_number'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Human-readable label, e.g. HEALIX-DEVICE-001', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'device_tokens',
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate in BPM.', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C.', max_digits=4, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, help_text='Blood oxygen saturation percentage (SpO2 %).', null=True)),
                ('device_id', models.CharField(blank=True, help_text='Identifier of the physical device that sent this reading.', max_length=100)),
                ('is_fever', models.BooleanField(default=False, help_text='Temperature > 38°C')),
                ('is_tachycardia', models.BooleanField(default=False, help_text='Heart rate > 110 BPM')),
                ('is_low_spo2', models.BooleanField(default=False, help_text='SpO2 < 95%')),
                ('has_alert', models.BooleanField(default=False, help_text='Any alert flag is true')),
                ('recorded_at', models.DateTimeField(help_text='When the device actually measured this (device clock).')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When the server received this reading.')),
                ('appointment', models.ForeignKey(blank=True, help_text='If taken during an appointment session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_readings', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'vital_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='vital_readi_patient_800333_idx'), models.Index(fields=['appointment', '-recorded_at'], name='vital_readi_appoint_aaa48a_idx'), models.Index(fields=['has_alert', '-recorded_at'], name='vital_readi_has_ale_e43a03_idx')],
            },
        ),
    ]
